name: Python Linting

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'

     - name: Install pipx
       run: python -m pip install --user pipx

     - name: Install poetry
       run: pipx install poetry==1.8.4

     - name: Install dependencies
       run: poetry install --with dev

     - name: Lint with ruff
       run: poetry run ruff check src alembic